### ISSUE TITLE
More docs?

### ISSUE THREAD

**Issue by AndreMaz** [google/splot-java#4]
Are there any additional docs? I'm especially interested in `automation pairings` and `automation rules`
What do they look like? What is their internal components? 

Also, what vocabulary is being used to express the values (`v` and `d`)? Is it based on SenML?
```JSON
{"onof":{"v":false},"levl":{"v":0.2},"tran":{"d":0}}
```

PS: I think that `Functional Endpoint` illustrated in [som-objects.png](https://github.com/google/splot-java/blob/master/doc/images/som-objects.png) is missing a self connection because `Functional Endpoint` can generate children, which are also `Functional Endpoint`

**Comment by darconeous** [comment]
> Are there any additional docs? I'm especially interested in `automation pairings` and `automation rules`

More detailed documentation is forthcoming, but in the mean time I can direct you to the preliminary Javadocs and sources for pairings and rules traits:

* [AutomationRuleTrait](https://google.github.io/splot-java/releases/latest/apidocs/reference/com/google/iot/m2m/trait/AutomationRuleTrait.html) ([source](https://github.com/google/splot-java/blob/master/splot-traits/src/main/java/com/google/iot/m2m/trait/AutomationRuleTrait.java))
* [AutomationPairingTrait](https://google.github.io/splot-java/releases/latest/apidocs/reference/com/google/iot/m2m/trait/AutomationPairingTrait.html) ([source](https://github.com/google/splot-java/blob/master/splot-traits/src/main/java/com/google/iot/m2m/trait/AutomationPairingTrait.java))

Both are still a work-in-progress.

> Also, what vocabulary is being used to express the values (`v` and `d`)? Is it based on SenML?

No, those are the property identifiers for those specific properties, which are defined by the trait. See [this](https://github.com/google/splot-java/blob/master/splot-traits/src/main/java/com/google/iot/m2m/trait/OnOffTrait.java#L60-L62), for example.

There is a convention of using `v` for the primary "value" of the trait, but not all traits have such a "primary" value. 

> PS: I think that `Functional Endpoint` illustrated in [som-objects.png](https://github.com/google/splot-java/blob/master/doc/images/som-objects.png) is missing a self connection because `Functional Endpoint` can generate children, which are also `Functional Endpoint`

Yes, indeed it is missing that connection. I'll track fixing that with this issue.

**Comment by AndreMaz** [comment]
Thanks for quick reply and for pointing out the location of javadocs. Looking forward to see more

The `AutomationRuleTrait` seems to be a 1-to-1 mechanism. I'm I right?
Are you considering 1-to-many situations?

**Comment by darconeous** [comment]
I'm not quite sure what you mean by 1:1 vs 1:many, as it applies to this case.

The automation rule can trigger actions on groups, which means that it can (when triggered) perform the same action on of the devices in the specified group.

**Comment by AndreMaz** [comment]
Sorry, poor choice of words. In 1:many I was referring to many heterogeneous devices. 
I will try to explain better what I mean.

Maybe I'm missing something but the `Group` resource simply forwards the `Rule's` action to a set of `Functional Endpoints` managed by the `Group`. Am I right ?
So a `Group` can solve the situation where one `on/off button` controls multiple lights.
![splot](https://user-images.githubusercontent.com/9802754/51970950-00ceca00-2470-11e9-997c-0258a1409359.png)

My doubt is how to model a situation when a single `Rule` can trigger state change of multiple heterogeneous devices.
A dummy example: the location of my phone triggering: 
1) lights `On` 
2) setting the AC temperature to `23`ºC

Is this something that can be modeled by splot model? If so, how?
It seem that the current solution to this use case would be having 2 rules (one to interact with the light and another with the AC).
![splot1](https://user-images.githubusercontent.com/9802754/51970971-0a583200-2470-11e9-987d-4ab76da5a0fe.png)

Another possible solution: modify the rule behavior and allow it to trigger multiple actions.
![splot2](https://user-images.githubusercontent.com/9802754/51970982-0e844f80-2470-11e9-8544-8577dd239dbc.png)

Or, yet another solution, have something like IoTivity's [Scene](https://wiki.iotivity.org/scene_manager). A Scene is basically a collection of <notification payload, destination> pairs.  When a Scene is triggered each notification is sent to the desired destination.
![splot3](https://user-images.githubusercontent.com/9802754/51970993-15ab5d80-2470-11e9-94c0-3053695eff00.png)

**Comment by darconeous** [comment]
The [latest release](https://github.com/google/splot-java/blob/master/CHANGELOG.md#version-00200) includes implementations of three automation primitives: Pairings, timers, and rules. Timers and rules can trigger multiple actions (which are now handled via the [ActionsTrait](https://google.github.io/splot-java/releases/latest/apidocs/reference/com/google/iot/m2m/trait/ActionsTrait.html)).

An introduction document can be found [here](https://github.com/google/splot-java/blob/master/doc/automation.md). 

The [JavaDocs](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/packages.html) also have a lot more information:

Primitive Traits:

* [AutomationPairingTrait](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/trait/AutomationPairingTrait.html)
* [AutomationRuleTrait](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/trait/AutomationRuleTrait.html)
* [AutomationTimerTrait](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/trait/AutomationTimerTrait.html)
* [ActionsTrait](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/trait/ActionsTrait.html)

Manager Traits (used to create and delete the associated automation primitives):

* [AutomationPairingManagerTrait](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/trait/AutomationPairingManagerTrait.html)
* [AutomationRuleManagerTrait](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/trait/AutomationRuleManagerTrait.html)
* [AutomationTimerManagerTrait](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/trait/AutomationTimerManagerTrait.html)

Automation primitive implementations:

* [LocalPairing](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/local/LocalPairing.html)
* [LocalRule](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/local/LocalRule.html)
* [LocalTimer](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/local/LocalTimer.html)
* [LocalAutomationManager](https://google.github.io/splot-java/releases/0.02.00/apidocs/reference/com/google/iot/m2m/local/LocalAutomationManager.html)

------

It sounds like IoTivity's scenes are a combination of the Splot concept of groups and scenes. A scene itself is a named set of state properties for a FunctionalEndpoint. By adding a FunctionalEndpoint to a group, you can recall a single scene on all of the FunctionalEndpoints in the group. This allows for practically instantaneous scene changes when a scene is recalled using a multicast packet.

**Comment by darconeous** [comment]
There is a great deal more documentation now available in the draft of the [Splot design Documentation](https://google.github.io/splot-java/splot-book/), so I'm going to go ahead and close this issue.
